In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re

%matplotlib inline

In [2]:
November = pd.read_csv('November_2017.csv')

In [3]:
df = pd.read_csv('/Users/TekendraMBP/Downloads/taxi_zone_lookup.csv')

In [4]:
November =  November.merge(df, left_on='PULocationID' , right_on='LocationID')

In [5]:
November.rename(columns={'LocationID' : "Pickup_Location_ID" , 'Borough' : 'Pickup_Borough' , 'Zone' : 'Pickup_Zone' , 'service_zone' : 'Pickup_Service_Zone'} , inplace=True)

In [6]:
November = November.merge(df, left_on='DOLocationID' , right_on='LocationID')

In [7]:
November.rename(columns={'LocationID' : "DropOff_Location_ID" , 'Borough' : 'DropOff_Borough' , 'Zone' : 'DropOff_Zone' , 'service_zone' : 'DropOff_Service_Zone'} , inplace=True)

In [8]:
November.drop(columns='PULocationID', inplace=True )

In [9]:
November.drop(columns='DOLocationID', inplace=True )

In [10]:
November.payment_type.replace(1 , 'credit_card' , inplace=True)
November.payment_type.replace(2 , 'cash' , inplace=True)
November.payment_type.replace(3 , 'no_charge' , inplace=True)
November.payment_type.replace(4 , 'dispute', inplace=True)
November.payment_type.replace(5 , 'unknown', inplace=True)
November.payment_type.replace(6 , 'voided_trip', inplace=True)

In [11]:
November.RatecodeID.replace(1 , 'standard_rate' , inplace=True)
November.RatecodeID.replace(2 , 'JFK' , inplace=True)
November.RatecodeID.replace(3 , 'Newark' , inplace=True)
November.RatecodeID.replace(4 , 'Nassau_or_Westchester', inplace=True)
November.RatecodeID.replace(5 , 'negotiated_fare', inplace=True)
November.RatecodeID.replace(6 , 'group_ride', inplace=True)

In [12]:
November.rename(columns={'tpep_pickup_datetime' : 'Pickup_Time' , 'tpep_dropoff_datetime' : 'DropOff_Time'} , inplace=True)

In [13]:
November = November[November['payment_type'] == 'credit_card']

In [14]:
November.dropna(inplace=True)

In [15]:
November = November[November['RatecodeID'] == 'standard_rate']

In [16]:
November.to_csv('November_Cleaned.csv' , index=False)

# Checkpoint 1: The entire month of November is cleaned

<i> now it's time to pull out the holidays for November 2017. Thanksgiving was on 23/11/2017. So if people were off on 22/11/2017 and the Sunday of that week was 26/11/2017 I want to pull out everything in between those dates

In [17]:
November

,VendorID,Pickup_Time,DropOff_Time,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,...,improvement_surcharge,total_amount,Pickup_Location_ID,Pickup_Borough,Pickup_Zone,Pickup_Service_Zone,DropOff_Location_ID,DropOff_Borough,DropOff_Zone,DropOff_Service_Zone
1,1,2017-11-01 00:02:47,2017-11-01 00:04:28,1,0.30,standard_rate,N,credit_card,3.5,0.5,...,0.3,6.00,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
9,2,2017-11-01 06:25:55,2017-11-01 06:26:23,2,0.29,standard_rate,N,credit_card,3.0,0.0,...,0.3,4.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
10,2,2017-11-01 06:57:23,2017-11-01 07:09:15,5,2.41,standard_rate,N,credit_card,10.5,0.0,...,0.3,14.69,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
12,2,2017-11-01 07:55:07,2017-11-01 08:01:48,1,0.90,standard_rate,N,credit_card,6.0,0.0,...,0.3,6.80,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
13,2,2017-11-01 07:11:21,2017-11-01 07:19:13,1,1.53,standard_rate,N,credit_card,8.0,0.0,...,0.3,10.56,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
14,1,2017-11-01 08:25:16,2017-11-01 08:36:46,2,1.50,standard_rate,N,credit_card,9.5,0.0,...,0.3,11.38,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
16,2,2017-11-01 08:32:51,2017-11-01 08:37:34,1,0.60,standard_rate,N,credit_card,5.0,0.0,...,0.3,6.96,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
19,2,2017-11-01 08:52:25,2017-11-01 08:57:50,1,0.60,standard_rate,N,credit_card,5.5,0.0,...,0.3,7.24,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
25,1,2017-11-01 09:41:44,2017-11-01 09:45:47,1,0.50,standard_rate,N,credit_card,4.5,0.0,...,0.3,7.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
28,2,2017-11-01 09:59:00,2017-11-01 10:03:06,2,0.54,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.40,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
29,2,2017-11-01 10:49:56,2017-11-01 10:57:33,2,0.26,standard_rate,N,credit_card,6.0,0.0,...,0.3,8.16,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
33,2,2017-11-01 12:30:03,2017-11-01 12:31:36,5,0.31,standard_rate,N,credit_card,3.5,0.0,...,0.3,5.16,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
35,1,2017-11-01 12:40:30,2017-11-01 12:42:15,2,0.40,standard_rate,N,credit_card,3.5,0.0,...,0.3,5.35,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
37,2,2017-11-01 13:47:17,2017-11-01 13:52:44,6,0.50,standard_rate,N,credit_card,5.5,0.0,...,0.3,7.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
39,2,2017-11-01 14:03:42,2017-11-01 14:06:58,2,0.56,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.36,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
40,1,2017-11-01 14:00:09,2017-11-01 14:05:33,1,0.80,standard_rate,N,credit_card,5.5,0.0,...,0.3,7.55,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
43,1,2017-11-01 15:54:11,2017-11-01 15:55:22,1,0.20,standard_rate,N,credit_card,3.0,0.0,...,0.3,4.90,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
44,2,2017-11-01 15:39:55,2017-11-01 15:44:13,1,0.41,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.36,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
45,1,2017-11-01 15:28:37,2017-11-01 15:32:18,1,0.40,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.35,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
46,2,2017-11-01 15:05:01,2017-11-01 15:18:49,1,1.36,standard_rate,N,credit_card,10.0,0.0,...,0.3,12.96,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
49,1,2017-11-01 16:41:16,2017-11-01 16:44:34,1,0.50,standard_rate,N,credit_card,4.0,1.0,...,0.3,7.25,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
51,2,2017-11-01 17:47:49,2017-11-01 17:51:41,1,0.58,standard_rate,N,credit_card,4.5,1.0,...,0.3,6.90,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
52,1,2017-11-01 17:33:54,2017-11-01 18:00:40,1,3.70,standard_rate,N,credit_card,18.5,1.0,...,0.3,24.36,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
54,2,2017-11-01 17:17:07,2017-11-01 17:19:06,1,0.31,standard_rate,N,credit_card,3.5,1.0,...,0.3,5.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
56,1,2017-11-01 17:30:54,2017-11-01 17:36:01,1,0.60,standard_rate,N,credit_card,5.0,1.0,...,0.3,8.15,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
57,2,2017-11-01 17:50:34,2017-11-01 17:53:47,2,0.60,standard_rate,N,credit_card,4.5,1.0,...,0.3,7.00,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
59,2,2017-11-01 17:29:48,2017-11-01 17:32:53,1,0.50,standard_rate,N,credit_card,4.0,1.0,...,0.3,6.96,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
62,2,2017-11-01 16:59:12,2017-11-01 17:01:26,1,0.34,standard_rate,N,credit_card,3.5,1.0,...,0.3,6.89,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
64,2,2017-11-01 17:45:45,2017-11-01 17:51:07,1,0.77,standard_rate,N,credit_card,5.5,1.0,...,0.3,9.49,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
65,1,2017-11-01 18:03:54,2017-11-01 18:05:43,1,0.30,standard_rate,N,credit_card,3.5,1.0,...,0.3,5.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9284752,2,2017-11-11 13:51:24,2017-11-11 14:40:47,1,15.87,standard_rate,N,credit_card,45.5,0.0,...,0.3,48.30,75,Manhattan,East Harlem South,Boro Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284755,2,2017-11-19 06:41:56,2017-11-19 07:02:04,5,14.42,standard_rate,N,credit_card,39.0,0.0,...,0.3,49.71,238,Manhattan,Upper West Side North,Yellow Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284756,2,2017-11-03 18:23:51,2017-11-03 18:56:28,1,8.50,standard_rate,N,credit_card,29.5,1.0,...,0.3,37.56,74,Manhattan,East Harlem North,Boro Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284758,1,2017-11-18 01:34:18,2017-11-18 01:46:32,2,8.70,standard_rate,N,credit_card,24.5,0.5,...,0.3,27.80,74,Manhattan,East Harlem North,Boro Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284759,2,2017-11-06 16:21:59,2017-11-06 17:13:40,6,9.77,standard_rate,N,credit_card,38.5,1.0,...,0.3,40.30,262,Manhattan,Yorkville East,Yellow Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284760,1,2017-11-03 19:28:29,2017-11-03 20:20:49,1,10.00,standard_rate,N,credit_card,46.0,1.0,...,0.3,63.56,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284761,2,2017-11-05 12:50:12,2017-11-05 13:10:17,1,12.39,standard_rate,N,credit_card,34.5,0.0,...,0.3,41.06,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284762,2,2017-11-10 10:26:30,2017-11-10 10:46:30,1,12.46,standard_rate,N,credit_card,34.0,0.0,...,0.3,45.56,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284763,2,2017-11-11 13:25:41,2017-11-11 13:47:48,5,11.95,standard_rate,N,credit_card,34.0,0.0,...,0.3,48.67,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284765,2,2017-11-11 17:15:55,2017-11-11 17:33:01,1,9.65,standard_rate,N,credit_card,28.0,0.0,...,0.3,40.00,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284766,1,2017-11-15 23:38:38,2017-11-16 00:06:56,1,13.20,standard_rate,N,credit_card,38.5,0.5,...,0.3,53.56,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284767,2,2017-11-18 21:24:03,2017-11-18 21:44:48,2,12.30,standard_rate,N,credit_card,34.0,0.5,...,0.3,41.06,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284769,1,2017-11-23 07:56:29,2017-11-23 08:13:41,2,11.50,standard_rate,N,credit_card,31.5,0.0,...,0.3,38.06,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284773,1,2017-11-18 08:10:51,2017-11-18 08:18:38,1,4.00,standard_rate,N,credit_card,12.5,0.0,...,0.3,14.30,248,Bronx,West Farms/Bronx River,Boro Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284774,2,2017-11-06 23:03:59,2017-11-06 23:05:55,1,0.45,standard_rate,N,credit_card,3.5,0.5,...,0.3,6.24,184,Bronx,Pelham Bay Park,Boro Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284775,2,2017-11-09 00:47:40,2017-11-09 00:52:18,1,0.60,standard_rate,N,credit_card,5.0,0.5,...,0.3,7.56,184,Bronx,Pelham Bay Park,Boro Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284780,1,2017-11-23 00:50:58,2017-11-23 01:26:11,1,23.80,standard_rate,N,credit_card,63.5,0.5,...,0.3,91.57,113,Manhattan,Greenwich Village North,Yellow Zone,99,Staten Island,Freshkills Park,Boro Zone
9284781,1,2017-11-15 20:41:13,2017-11-15 21:20:25,2,26.70,standard_rate,N,credit_card,72.5,0.5,...,0.3,113.75,161,Manhattan,Midtown Center,Yellow Zone,99,Staten Island,Freshkills Park,Boro Zone
9284782,2,2017-11-16 00:18:34,2017-11-16 01:00:43,5,26.59,standard_rate,N,credit_card,72.0,0.5,...,0.3,101.78,107,Manhattan,Gramercy,Yellow Zone,99,Staten Island,Freshkills Park,Boro Zone
9284783,1,2017-11-17 23:38:44,2017-11-18 00:34:48,1,26.70,standard_rate,N,credit_card,74.5,0.5,...,0.3,104.77,107,Manhattan,Gramercy,Yellow Zone,99,Staten Island,Freshkills Park,Boro Zone
9284785,2,2017-11-22 09:24:44,2017-11-22 09:37:56,3,3.67,standard_rate,N,credit_card,13.5,0.0,...,0.3,17.16,79,Manhattan,East Village,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284786,2,2017-11-08 10:48:27,2017-11-08 11:14:36,5,4.88,standard_rate,N,credit_card,20.0,0.0,...,0.3,21.80,170,Manhattan,Murray Hill,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284788,1,2017-11-02 11:34:26,2017-11-02 11:53:57,1,8.80,standard_rate,N,credit_card,26.0,0.0,...,0.3,32.15,75,Manhattan,East Harlem South,Boro Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284789,2,2017-11-20 09:28:59,2017-11-20 09:37:07,1,0.77,standard_rate,N,credit_card,6.5,0.0,...,0.3,8.40,231,Manhattan,TriBeCa/Civic Center,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284792,2,2017-11-28 06:38:52,2017-11-28 07:08:32,1,10.17,standard_rate,N,credit_card,32.5,0.0,...,0.3,35.30,260,Queens,Woodside,Boro Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284793,2,2017-11-29 08:18:34,2017-11-29 08:36:44,1,5.00,standard_rate,N,credit_card,18.5,0.0,...,0.3,21.81,262,Manhattan,Yorkville East,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284795,1,2017-11-06 19:43:55,2017-11-06 19:50:56,1,1.00,standard_rate,N,credit_card,6.5,1.0,...,0.3,9.95,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284798,1,2017-11-06 20:26:20,2017-11-06 20:29:59,1,0.90,standard_rate,N,credit_card,5.0,0.5,...,0.3,7.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284799,1,2017-11-06 20:31:04,2017-11-06 20:35:41,1,0.80,standard_rate,N,credit_card,5.0,0.5,...,0.3,7.55,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
9284801,1,2017-11-06 21:04:10,2017-11-06 21:35:08,1,6.10,standard_rate,N,credit_card,24.0,0.5,...,0.3,28.80,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone

In [18]:
November[November['Pickup_Time'].str.contains(r'(2017-11-23).*')]

/Users/TekendraMBP/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

,VendorID,Pickup_Time,DropOff_Time,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,...,improvement_surcharge,total_amount,Pickup_Location_ID,Pickup_Borough,Pickup_Zone,Pickup_Service_Zone,DropOff_Location_ID,DropOff_Borough,DropOff_Zone,DropOff_Service_Zone
2877,2,2017-11-23 00:38:18,2017-11-23 00:45:06,1,0.82,standard_rate,N,credit_card,5.5,0.5,...,0.3,10.80,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2878,2,2017-11-23 01:28:45,2017-11-23 01:33:16,3,0.84,standard_rate,N,credit_card,5.0,0.5,...,0.3,10.00,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2881,2,2017-11-23 04:23:25,2017-11-23 04:25:16,1,0.19,standard_rate,N,credit_card,3.5,0.5,...,0.3,6.00,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2882,1,2017-11-23 04:10:09,2017-11-23 04:11:03,1,0.10,standard_rate,N,credit_card,3.0,0.5,...,0.3,5.55,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2883,2,2017-11-23 06:59:03,2017-11-23 07:01:22,1,0.48,standard_rate,N,credit_card,4.0,0.0,...,0.3,5.76,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2884,2,2017-11-23 07:30:05,2017-11-23 07:32:13,1,0.44,standard_rate,N,credit_card,3.5,0.0,...,0.3,5.16,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2885,2,2017-11-23 08:17:21,2017-11-23 08:18:53,1,0.44,standard_rate,N,credit_card,3.5,0.0,...,0.3,5.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2886,2,2017-11-23 08:38:45,2017-11-23 08:40:04,1,0.34,standard_rate,N,credit_card,3.0,0.0,...,0.3,4.80,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2887,2,2017-11-23 08:46:16,2017-11-23 08:49:57,1,0.49,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.36,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2889,2,2017-11-23 09:54:42,2017-11-23 09:57:38,1,0.78,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2890,2,2017-11-23 09:05:41,2017-11-23 09:09:28,1,0.82,standard_rate,N,credit_card,5.0,0.0,...,0.3,7.80,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2891,2,2017-11-23 09:57:50,2017-11-23 10:06:07,1,1.68,standard_rate,N,credit_card,8.0,0.0,...,0.3,10.56,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2892,2,2017-11-23 09:56:46,2017-11-23 09:59:05,1,0.39,standard_rate,N,credit_card,3.5,0.0,...,0.3,5.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2893,2,2017-11-23 09:01:18,2017-11-23 09:05:29,2,0.49,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.36,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2895,2,2017-11-23 10:31:31,2017-11-23 10:35:13,1,0.52,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2896,2,2017-11-23 10:22:16,2017-11-23 10:25:38,1,0.26,standard_rate,N,credit_card,4.0,0.0,...,0.3,5.76,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2902,1,2017-11-23 11:20:41,2017-11-23 11:25:02,1,0.80,standard_rate,N,credit_card,5.0,0.0,...,0.3,6.67,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2905,1,2017-11-23 11:26:56,2017-11-23 11:39:35,1,1.70,standard_rate,N,credit_card,10.5,0.0,...,0.3,12.43,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2907,2,2017-11-23 11:06:19,2017-11-23 11:11:56,1,0.85,standard_rate,N,credit_card,5.5,0.0,...,0.3,8.19,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2910,2,2017-11-23 12:10:21,2017-11-23 12:14:09,1,0.68,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2912,2,2017-11-23 13:16:19,2017-11-23 13:20:50,2,0.89,standard_rate,N,credit_card,5.0,0.0,...,0.3,7.80,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2913,2,2017-11-23 13:10:36,2017-11-23 13:14:08,1,0.62,standard_rate,N,credit_card,4.5,0.0,...,0.3,5.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2914,2,2017-11-23 13:49:07,2017-11-23 13:53:02,1,0.55,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.36,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2915,2,2017-11-23 13:29:09,2017-11-23 13:33:34,2,0.66,standard_rate,N,credit_card,5.0,0.0,...,0.3,6.96,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2918,2,2017-11-23 14:37:52,2017-11-23 14:40:10,2,0.53,standard_rate,N,credit_card,4.0,0.0,...,0.3,5.76,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2919,2,2017-11-23 14:39:03,2017-11-23 14:43:42,1,0.69,standard_rate,N,credit_card,5.5,0.0,...,0.3,8.30,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2920,1,2017-11-23 14:35:15,2017-11-23 14:36:21,1,0.40,standard_rate,N,credit_card,3.0,0.0,...,0.3,4.55,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2922,2,2017-11-23 14:13:13,2017-11-23 14:23:44,1,0.40,standard_rate,N,credit_card,7.5,0.0,...,0.3,11.49,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2923,1,2017-11-23 14:09:05,2017-11-23 14:12:22,1,0.60,standard_rate,N,credit_card,4.5,0.0,...,0.3,6.35,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
2927,2,2017-11-23 15:55:20,2017-11-23 16:00:56,1,0.86,standard_rate,N,credit_card,5.5,0.0,...,0.3,7.88,151,Manhattan,Manhattan Valley,Yellow Zone,151,Manhattan,Manhattan Valley,Yellow Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9282410,2,2017-11-23 07:55:33,2017-11-23 08:11:42,2,6.69,standard_rate,N,credit_card,21.5,0.0,...,0.3,26.76,132,Queens,JFK Airport,Airports,203,Queens,Rosedale,Boro Zone
9282411,1,2017-11-23 08:02:12,2017-11-23 08:12:02,1,5.90,standard_rate,N,credit_card,17.0,0.0,...,0.3,22.80,132,Queens,JFK Airport,Airports,203,Queens,Rosedale,Boro Zone
9282412,2,2017-11-23 13:47:11,2017-11-23 14:04:08,1,5.57,standard_rate,N,credit_card,19.0,0.0,...,0.3,23.76,132,Queens,JFK Airport,Airports,203,Queens,Rosedale,Boro Zone
9282420,1,2017-11-23 19:45:01,2017-11-23 19:57:47,1,6.60,standard_rate,N,credit_card,20.0,0.0,...,0.3,22.80,132,Queens,JFK Airport,Airports,203,Queens,Rosedale,Boro Zone
9282424,2,2017-11-23 21:27:10,2017-11-23 21:37:56,1,5.02,standard_rate,N,credit_card,16.0,0.5,...,0.3,20.76,132,Queens,JFK Airport,Airports,203,Queens,Rosedale,Boro Zone
9282570,2,2017-11-23 00:33:09,2017-11-23 01:00:03,1,17.61,standard_rate,N,credit_card,47.5,0.5,...,0.3,54.56,233,Manhattan,UN/Turtle Bay South,Yellow Zone,203,Queens,Rosedale,Boro Zone
9282824,2,2017-11-23 00:21:41,2017-11-23 00:56:46,6,18.12,standard_rate,N,credit_card,52.0,0.5,...,0.3,59.06,230,Manhattan,Times Sq/Theatre District,Yellow Zone,205,Queens,Saint Albans,Boro Zone
9283304,2,2017-11-23 09:03:24,2017-11-23 09:14:00,1,4.39,standard_rate,N,credit_card,14.5,0.0,...,0.3,18.36,132,Queens,JFK Airport,Airports,205,Queens,Saint Albans,Boro Zone
9283305,2,2017-11-23 12:37:38,2017-11-23 12:50:02,5,4.02,standard_rate,N,credit_card,14.0,0.0,...,0.3,17.76,132,Queens,JFK Airport,Airports,205,Queens,Saint Albans,Boro Zone
9283316,2,2017-11-23 22:37:56,2017-11-23 22:54:05,1,5.26,standard_rate,N,credit_card,17.5,0.5,...,0.3,23.50,132,Queens,JFK Airport,Airports,205,Queens,Saint Albans,Boro Zone
9283647,2,2017-11-23 20:06:10,2017-11-23 20:33:49,1,11.95,standard_rate,N,credit_card,35.5,0.5,...,0.3,44.16,138,Queens,LaGuardia Airport,Airports,205,Queens,Saint Albans,Boro Zone
9283737,2,2017-11-23 09:50:03,2017-11-23 09:58:42,5,2.45,standard_rate,N,credit_card,9.5,0.0,...,0.3,10.30,219,Queens,Springfield Gardens South,Boro Zone,205,Queens,Saint Albans,Boro Zone
9283761,1,2017-11-23 00:25:12,2017-11-23 01:16:25,2,18.50,standard_rate,N,credit_card,56.5,0.5,...,0.3,83.17,148,Manhattan,Lower East Side,Yellow Zone,176,Staten Island,Oakwood,Boro Zone
9283773,2,2017-11-23 06:49:41,2017-11-23 07:36:25,1,27.03,standard_rate,N,credit_card,73.5,0.0,...,0.3,102.98,132,Queens,JFK Airport,Airports,176,Staten Island,Oakwood,Boro Zone
9283791,2,2017-11-23 03:17:14,2017-11-23 04:06:30,1,19.84,standard_rate,N,credit_card,58.0,0.5,...,0.3,84.98,90,Manhattan,Flatiron,Yellow Zone,176,Staten Island,Oakwood,Boro Zone
9283848,1,2017-11-23 02:24:46,2017-11-23 03:09:11,1,27.10,standard_rate,N,credit_card,72.5,0.5,...,0.3,85.96,230,Manhattan,Times Sq/Theatre District,Yellow Zone,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
9283849,1,2017-11-23 03:15:58,2017-11-23 03:56:08,1,23.10,standard_rate,N,credit_card,64.0,0.5,...,0.3,72.46,230,Manhattan,Times Sq/Theatre District,Yellow Zone,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
9283954,2,2017-11-23 01:47:00,2017-11-23 02:26:45,1,19.15,standard_rate,N,credit_card,54.0,0.5,...,0.3,72.58,158,Manhattan,Meatpacking/West Village West,Yellow Zone,109,Staten Island,Great Kills,Boro Zone
9283958,1,2017-11-23 02:31:26,2017-11-23 03:11:14,1,19.30,standard_rate,N,credit_card,54.0,0.5,...,0.3,72.58,114,Manhattan,Greenwich Village South,Yellow Zone,109,Staten Island,Great Kills,Boro Zone
9283969,2,2017-11-23 12:27:13,2017-11-23 13:16:19,1,19.20,standard_rate,N,credit_card,54.5,0.0,...,0.3,66.82,4,Manhattan,Alphabet City,Yellow Zone,109,Staten Island,Great Kills,Boro Zone
9284024,2,2017-11-23 00:42:01,2017-11-23 01:12:56,2,11.45,standard_rate,N,credit_card,34.5,0.5,...,0.3,42.96,48,Manhattan,Clinton East,Yellow Zone,111,Brooklyn,Green-Wood Cemetery,Boro Zone
9284025,1,2017-11-23 14:26:27,2017-11-23 15:17:26,1,9.50,standard_rate,N,credit_card,40.0,0.0,...,0.3,45.80,48,Manhattan,Clinton East,Yellow Zone,111,Brooklyn,Green-Wood Cemetery,Boro Zone
9284045,1,2017-11-23 21:18:04,2017-11-23 21:58:30,3,13.40,standard_rate,N,credit_card,42.5,0.5,...,0.3,54.75,166,Manhattan,Morningside Heights,Boro Zone,111,Brooklyn,Green-Wood Cemetery,Boro Zone
9284055,2,2017-11-23 23:41:44,2017-11-23 23:44:17,2,0.95,standard_rate,N,credit_card,5.0,0.5,...,0.3,9.51,181,Brooklyn,Park Slope,Boro Zone,111,Brooklyn,Green-Wood Cemetery,Boro Zone
9284705,2,2017-11-23 20:54:53,2017-11-23 21:20:50,2,9.99,standard_rate,N,credit_card,30.5,0.5,...,0.3,40.11,14,Brooklyn,Bay Ridge,Boro Zone,154,Brooklyn,Marine Park/Floyd Bennett Field,Boro Zone
9284707,2,2017-11-23 00:38:43,2017-11-23 01:11:10,1,21.04,standard_rate,N,credit_card,56.5,0.5,...,0.3,60.80,138,Queens,LaGuardia Airport,Airports,154,Brooklyn,Marine Park/Floyd Bennett Field,Boro Zone
9284708,1,2017-11-23 18:37:26,2017-11-23 19:05:21,1,17.70,standard_rate,N,credit_card,47.5,0.0,...,0.3,55.80,138,Queens,LaGuardia Airport,Airports,154,Brooklyn,Marine Park/Floyd Bennett Field,Boro Zone
9284737,2,2017-11-23 22:19:44,2017-11-23 22:56:13,1,13.89,standard_rate,N,credit_card,41.0,0.5,...,0.3,42.30,186,Manhattan,Penn Station/Madison Sq West,Yellow Zone,184,Bronx,Pelham Bay Park,Boro Zone
9284769,1,2017-11-23 07:56:29,2017-11-23 08:13:41,2,11.50,standard_rate,N,credit_card,31.5,0.0,...,0.3,38.06,138,Queens,LaGuardia Airport,Airports,184,Bronx,Pelham Bay Park,Boro Zone
9284780,1,2017-11-23 00:50:58,2017-11-23 01:26:11,1,23.80,standard_rate,N,credit_card,63.5,0.5,...,0.3,91.57,113,Manhattan,Greenwich Village North,Yellow Zone,99,Staten Island,Freshkills Park,Boro Zone

In [19]:
len(November[November['Pickup_Time'].str.contains(r'(2017-11-23).*')])

/Users/TekendraMBP/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

103379

In [31]:
def vacation_maker(row):
    if row[row['Pickup_Time'].str.contains(r'(2017-11-22).*')]: 
        val = 'Holiday'
    elif row[row['Pickup_Time'].str.contains(r'(2017-11-23).*')]: 
        val = 'Holiday'
    elif row[row['Pickup_Time'].str.contains(r'(2017-11-24).*')]: 
        val = 'Holiday'
    elif row[row['Pickup_Time'].str.contains(r'(2017-11-25).*')]: 
        val = 'Holiday'
    elif row[row['Pickup_Time'].str.contains(r'(2017-11-26).*')]: 
        val = 'Holiday'
    else:
        val = 'Workday'
    return val

In [32]:
November['Type_of_Day'] = November.apply(vacation_maker,axis=1 )

AttributeError: ("'str' object has no attribute 'str'", 'occurred at index 1')

In [26]:
November.dtypes

VendorID                   int64
Pickup_Time               object
DropOff_Time              object
passenger_count            int64
trip_distance            float64
RatecodeID                object
store_and_fwd_flag        object
payment_type              object
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
Pickup_Location_ID         int64
Pickup_Borough            object
Pickup_Zone               object
Pickup_Service_Zone       object
DropOff_Location_ID        int64
DropOff_Borough           object
DropOff_Zone              object
DropOff_Service_Zone      object
dtype: object